# Generated by Django 3.0.4 on 2020-03-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
    ]
