# Generated by Django 3.0.4 on 2020-03-10 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster', '0002_auto_20200310_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='character',
            new_name='characters',
        ),
        migrations.AddField(
            model_name='raid',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raid',
            name='raid',
            field=models.CharField(choices=[('MC', 'Mc'), ('BWL', 'Bwl')], default='MC', max_length=200),
            preserve_default=False,
        ),
    ]
