# Generated by Django 3.0.4 on 2020-03-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster', '0005_auto_20200310_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='character',
            new_name='raiders',
        ),
    ]
